(in-package :http-test)

(def-test-group path-trim-prefix ()
  (def-test case-1 (:equal "") (http::path-trim-prefix "foo" "/foo"))
  (def-test case-2 (:equal "") (http::path-trim-prefix "foo" "/foo/"))
  (def-test case-3 (:equal "bar") (http::path-trim-prefix "foo" "/foo/bar"))
  (def-test case-4 (:equal "bar") (http::path-trim-prefix "/foo" "/foo/bar"))
  (def-test case-5 (:equal "bar") (http::path-trim-prefix "foo/" "/foo/bar"))
  (def-test case-6 (:equal "bar") (http::path-trim-prefix "/foo/" "/foo/bar"))
  (def-test case-7 (:equal "") (http::path-trim-prefix "/foo/bar" "/foo/bar"))
  (def-test case-8 (:equal "") (http::path-trim-prefix "/foo/bar" "/foo/bar/"))
  (def-test case-9 (:equal "") (http::path-trim-prefix "/foo/bar/" "/foo/bar"))
  (def-test case-10 (:equal "") (http::path-trim-prefix "/foo/bar/" "/foo/bar/"))
  (def-test case-11 (:equal nil) (http::path-trim-prefix "goo" "/foo/bar/"))
  (def-test case-12 (:equal "foo/bar/") (http::path-trim-prefix "/" "/foo/bar/"))
  (def-test case-13 (:equal "foo/bar") (http::path-trim-prefix "" "/foo/bar"))
  (def-test case-14 (:equal "foo/bar/") (http::path-trim-prefix nil "/foo/bar/")))
