(in-package :style)

;; https://drafts.csswg.org/css-box-3

(define-property margin-top ()
  ()
  (:value length percentage :auto))

(define-property margin-right ()
  ()
  (:value length percentage :auto))

(define-property margin-bottom ()
  ()
  (:value length percentage :auto))

(define-property margin-left ()
  ()
  (:value length percentage :auto))

;; TODO: proper handle (margin "1px 2px 3px 4px")
(defun margin (&rest values)
  (case (cl:length values)
    (1 `(,(margin-top (first values))
          ,(margin-right (first values))
          ,(margin-bottom (first values))
          ,(margin-left (first values))))
    (2 `(,(margin-top (first values))
          ,(margin-right (second values))
          ,(margin-bottom (first values))
          ,(margin-left (second values))))
    (3 `(,(margin-top (first values))
          ,(margin-right (second values))
          ,(margin-bottom (third values))
          ,(margin-left (second values))))
    (4 `(,(margin-top (first values))
          ,(margin-right (second values))
          ,(margin-bottom (third values))
          ,(margin-left (fourth values))))))

(define-property margin-trim ()
  ()
  (:value :none :in-flow :all))

(define-property padding-top ()
  ()
  (:value length percentage :auto))

(define-property padding-right ()
  ()
  (:value length percentage :auto))

(define-property padding-bottom ()
  ()
  (:value length percentage :auto))

(define-property padding-left ()
  ()
  (:value length percentage :auto))

;; TODO: proper handle (padding "1px 2px 3px 4px")
(defun padding (&rest values)
  (case (cl:length values)
    (1 `(,(padding-top (first values))
          ,(padding-right (first values))
          ,(padding-bottom (first values))
          ,(padding-left (first values))))
    (2 `(,(padding-top (first values))
          ,(padding-right (second values))
          ,(padding-bottom (first values))
          ,(padding-left (second values))))
    (3 `(,(padding-top (first values))
          ,(padding-right (second values))
          ,(padding-bottom (third values))
          ,(padding-left (second values))))
    (4 `(,(padding-top (first values))
          ,(padding-right (second values))
          ,(padding-bottom (third values))
          ,(padding-left (fourth values))))))
