(in-package :uri)

(defmacro uri (&body forms)
  (with-gensyms (values)
    `(let ((,values (list ,@forms)))
       (typecase (first ,values)
         (null nil)
         ((or string uri)
          (typecase (second ,values)
            (null (typecase (first ,values)
                    (uri (first ,values))
                    (string (parse-uri (first ,values)))))
            ((or string uri) (merge-uri (first ,values) (second ,values)))
            (keyword (apply 'update-uri (first ,values) (rest ,values)))))
         (keyword (apply 'make-uri ,values))))))
