(in-package :css-test)

(in-suite :css-test)

(test margin
  (margin-top (px 1))
  (margin-top "1px")
  (margin-right (px 1))
  (margin-right "1px")
  (margin-bottom (px 1))
  (margin-bottom "1px")
  (margin-left (px 1))
  (margin-left "1px")
  (margin (px 1))
  (margin (px 1) (px 2))
  (margin (px 1) (px 2) (px 3))
  (margin (px 1) (px 2) (px 3) (px 4))
  (margin "1px")
  (margin "1px 2px")
  (margin "1px 2px 3px")
  (margin "1px 2px 3px 4px"))

(test padding
  (padding-top (px 1))
  (padding-top "1px")
  (padding-right (px 1))
  (padding-right "1px")
  (padding-bottom (px 1))
  (padding-bottom "1px")
  (padding-left (px 1))
  (padding-left "1px")
  (padding (px 1))
  (padding (px 1) (px 2))
  (padding (px 1) (px 2) (px 3))
  (padding (px 1) (px 2) (px 3) (px 4))
  (padding "1px")
  (padding "1px 2px")
  (padding "1px 2px 3px")
  (padding "1px 2px 3px 4px"))
