(in-package :javascript)

(defparameter +message-bad-getter-arity+ "Getter must not have any formal parameters")
(defparameter +message-bad-setter-arity+ "Setter must have exactly one formal parameter")
(defparameter +message-bad-setter-rest-parameter+ "Setter function argument must not be a rest parameter")
(defparameter +message-constructor-is-async+ "Class constructor may not be an async method")
(defparameter +message-constructor-special-method+ "Class constructor may not be an accessor")
(defparameter +message-declaration-missing-initializer+ "Missing initializer in ~A declaration")
(defparameter +message-default-rest-parameter+ "Unexpected token =")
(defparameter +message-duplicate-binding+ "Duplicate binding ~A")
(defparameter +message-duplicate-constructor+ "A class may only have one constructor")
(defparameter +message-duplicate-proto-property+ "Duplicate __proto__ fields are not allowed in object literals")
(defparameter +message-for-in-of-loop-initializer+ "~A loop variable declaration may not have an initializer")
(defparameter +message-generator-in-legacy-context+ "Generator declarations are not allowed in legacy contexts")
(defparameter +message-illegal-break+ "Illegal break statement")
(defparameter +message-illegal-continue+ "Illegal continue statement")
(defparameter +message-illegal-export-declaration+ "Unexpected token")
(defparameter +message-illegal-import-declaration+ "Unexpected token")
(defparameter +message-illegal-language-mode-directive+ "Illegal 'use strict' directive in function with non-simple parameter list")
(defparameter +message-illegal-return+ "Illegal return statement")
(defparameter +message-invalid-escaped-reserved-word+ "Keyword must not contain escaped characters")
(defparameter +message-invalid-hex-escape-sequence+ "Invalid hexadecimal escape sequence")
(defparameter +message-invalid-lhs-in-assignment+ "Invalid left-hand side in assignment")
(defparameter +message-invalid-lhs-in-for-in+ "Invalid left-hand side in for-in")
(defparameter +message-invalid-lhs-in-for-loop+ "Invalid left-hand side in for-loop")
(defparameter +message-invalid-module-specifier+ "Unexpected token")
(defparameter +message-invalid-reg-exp+ "Invalid regular expression")
(defparameter +message-let-in-lexical-binding+ "let is disallowed as a lexically bound name")
(defparameter +message-missing-from-clause+ "Unexpected token")
(defparameter +message-multiple-defaults-in-switch+ "More than one default clause in switch statement")
(defparameter +message-newline-after-throw+ "Illegal newline after throw")
(defparameter +message-no-as-after-import-namespace+ "Unexpected token")
(defparameter +message-no-catch-or-finally+ "Missing catch or finally after try")
(defparameter +message-parameter-after-rest-parameter+ "Rest parameter must be last formal parameter")
(defparameter +message-redeclaration+ "~A '~A' has already been declared")
(defparameter +message-static-prototype+ "Classes may not have static property named prototype")
(defparameter +message-strict-catch-variable+ "Catch variable may not be eval or arguments in strict mode")
(defparameter +message-strict-delete+ "Delete of an unqualified identifier in strict mode.")
(defparameter +message-strict-function+ "In strict mode code, functions can only be declared at top level or inside a block")
(defparameter +message-strict-function-name+ "Function name may not be eval or arguments in strict mode")
(defparameter +message-strict-lhs-assignment+ "Assignment to eval or arguments is not allowed in strict mode")
(defparameter +message-strict-lhs-postfix+ "Postfix increment/decrement may not have eval or arguments operand in strict mode")
(defparameter +message-strict-lhs-prefix+ "Prefix increment/decrement may not have eval or arguments operand in strict mode")
(defparameter +message-strict-mode-with+ "Strict mode code may not include a with statement")
(defparameter +message-strict-octal-literal+ "Octal literals are not allowed in strict mode.")
(defparameter +message-strict-param-dupe+ "Strict mode function may not have duplicate parameter names")
(defparameter +message-strict-param-name+ "Parameter name eval or arguments is not allowed in strict mode")
(defparameter +message-strict-reserved-word+ "Use of future reserved word in strict mode")
(defparameter +message-strict-var-name+ "Variable name may not be eval or arguments in strict mode")
(defparameter +message-template-octal-literal+ "Octal literals are not allowed in template strings.")
(defparameter +message-unexpected-eos+ "Unexpected end of input")
(defparameter +message-unexpected-identifier+ "Unexpected identifier")
(defparameter +message-unexpected-number+ "Unexpected number")
(defparameter +message-unexpected-reserved+ "Unexpected reserved word")
(defparameter +message-unexpected-string+ "Unexpected string")
(defparameter +message-unexpected-template+ "Unexpected quasi ~A")
(defparameter +message-unexpected-token+ "Unexpected token ~A")
(defparameter +message-unexpected-token-illegal+ "Unexpected token ILLEGAL")
(defparameter +message-unknown-label+ "Undefined label '~A'")
(defparameter +message-unterminated-reg-exp+ "Invalid regular expression: missing /")
