%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.3.3

-ifndef(wt_proto_hello).
-define(wt_proto_hello, true).

-define(wt_proto_hello_gpb_version, "4.3.3").

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record('Person',
        {name                   :: iolist(),        % = 1
         id                     :: integer(),       % = 2, 32 bits
         email                  :: iolist() | undefined % = 3
        }).
-endif.

-endif.
