%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.3.3

-ifndef(wt_proto_http).
-define(wt_proto_http, true).

-define(wt_proto_http_gpb_version, "4.3.3").

-ifndef('REQUEST_PB_H').
-define('REQUEST_PB_H', true).
-record('Request',
        {local_address = []     :: iolist() | undefined, % = 1
         local_port = 0         :: non_neg_integer() | undefined, % = 2, 32 bits
         remote_address = []    :: iolist() | undefined, % = 3
         remote_port = 0        :: non_neg_integer() | undefined, % = 4, 32 bits
         scheme = 'HTTP'        :: 'HTTP' | 'HTTPS' | integer() | undefined, % = 5, enum Request.Schemes
         method = 'GET'         :: 'GET' | 'HEAD' | 'OPTIONS' | 'PUT' | 'POST' | 'DELETE' | integer() | undefined, % = 6, enum Request.Methods
         path = []              :: iolist() | undefined, % = 7
         query = []             :: iolist() | undefined, % = 8
         version = 'HTTP_1_0'   :: 'HTTP_1_0' | 'HTTP_1_1' | 'HTTP_2' | integer() | undefined, % = 9, enum Request.Versions
         headers = []           :: [{iolist(), iolist()}] | undefined, % = 10
         body = <<>>            :: iodata() | undefined % = 11
        }).
-endif.

-ifndef('RESPONSE_PB_H').
-define('RESPONSE_PB_H', true).
-record('Response',
        {type = 'REPLY'         :: 'REPLY' | 'STREAM' | 'SENDFILE' | integer() | undefined, % = 1, enum Response.Types
         code = 0               :: non_neg_integer() | undefined, % = 2, 32 bits
         headers = []           :: [{iolist(), iolist()}] | undefined, % = 3
         body = <<>>            :: iodata() | undefined, % = 4
         path = []              :: iolist() | undefined % = 5
        }).
-endif.

-endif.
