(in-package :component)

(define-component html-element ()
  ((tag
    :initarg :tag
    :initform nil)
   (attributes
    :initarg :attributes
    :initform nil)))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defmacro define-html-element-component (tag-name)
    `(progn
       (define-component ,tag-name (html-element) ())
       (define-render ,tag-name (tag attributes children)
         (apply (ensure-symbol (symbol-name tag) :html)
                (append attributes @children)))
       (defun ,tag-name (&rest attributes-and-children)
         (multiple-value-bind (attributes children)
             (html::segment-attributes-children attributes-and-children)
           (let ((html-element (make-instance ',tag-name
                                              :tag ,(make-keyword tag-name)
                                              :attributes attributes)))
             (loop for child in children
                do (append-child html-element child))
             html-element)))
       (export ',tag-name)
       ',tag-name)))


;; Content sectioning
(define-html-element-component address)
(define-html-element-component article)
(define-html-element-component aside)
(define-html-element-component footer)
(define-html-element-component header)
(define-html-element-component h1)
(define-html-element-component h2)
(define-html-element-component h3)
(define-html-element-component h4)
(define-html-element-component h5)
(define-html-element-component h6)
(define-html-element-component hgroup)
(define-html-element-component main)
(define-html-element-component nav)
(define-html-element-component section)

;; Text content
(define-html-element-component blockquote)
(define-html-element-component dd)
(define-html-element-component div)
(define-html-element-component dl)
(define-html-element-component dt)
(define-html-element-component figcaption)
(define-html-element-component figure)
(define-html-element-component hr)
(define-html-element-component li)
(define-html-element-component main)
(define-html-element-component ol)
(define-html-element-component p)
(define-html-element-component pre)
(define-html-element-component ul)

;; Inline text semantics
(define-html-element-component a)
(define-html-element-component abbr)
(define-html-element-component b)
(define-html-element-component bdi)
(define-html-element-component bdo)
(define-html-element-component br)
(define-html-element-component cite)
(define-html-element-component code)
(define-html-element-component data)
(define-html-element-component dfn)
(define-html-element-component em)
(define-html-element-component i)
(define-html-element-component kbd)
(define-html-element-component mark)
(define-html-element-component q)
(define-html-element-component rb)
(define-html-element-component rp)
(define-html-element-component rt)
(define-html-element-component rtc)
(define-html-element-component ruby)
(define-html-element-component s)
(define-html-element-component samp)
(define-html-element-component smail)
(define-html-element-component span)
(define-html-element-component strong)
(define-html-element-component sub)
(define-html-element-component sup)
(define-html-element-component u)
(define-html-element-component var)
(define-html-element-component wbr)

;; Table content
(define-html-element-component caption)
(define-html-element-component col)
(define-html-element-component colgroup)
(define-html-element-component table)
(define-html-element-component tbody)
(define-html-element-component td)
(define-html-element-component tfoot)
(define-html-element-component th)
(define-html-element-component thead)
(define-html-element-component tr)

;; Forms
(define-html-element-component datalist)
(define-html-element-component fieldset)
(define-html-element-component form)
(define-html-element-component input)
(define-html-element-component label)
(define-html-element-component legend)
(define-html-element-component meter)
(define-html-element-component optgroup)
(define-html-element-component option)
(define-html-element-component output)
(define-html-element-component progress)
(define-html-element-component select)
(define-html-element-component textarea)
